# Generated by Django 5.1.3 on 2024-11-21 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
