# Generated by Django 5.1.3 on 2024-11-21 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_about_views'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_type', models.CharField(choices=[('Gasoline', 'Автомобильные бензины'), ('Diesel', 'Дизельное топливо'), ('Mazut', 'Мазут'), ('Sulfur', 'Сера'), ('Solvent', 'Углеводородный растворитель')], max_length=50)),
                ('characteristics', models.TextField()),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
