# Generated by Django 5.1.3 on 2024-11-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('gasoline', 'Автомобильные бензины'), ('diesel', 'Дизельное топливо'), ('black_oil', 'Мазут'), ('sulfur', 'Сера'), ('solvent', 'Углеводородный растворитель')], max_length=50),
        ),
    ]
