export const CATEGORY = 'main/category'
export const SUBCATEGORY = 'main/subcategory/{id}'
export const ABOUT_DETAIL = 'main/about/{id}'
export const PRODUCTS = 'main/product'
export const PRODUCT_DETAIL = 'main/product/{id}'
